### ISSUE TITLE
建议增加64位的lib

### ISSUE THREAD

**Issue by duyirun9829** [cloudinjector/CloudInject#11]
根据安卓开发规范，软件要以64位为主
目前已测试在Android Studio里面的模拟器上无法安装
希望能增加arm64_v8a+x86_64的lib，这样可以使软件可在上述模拟器中安装
希望采纳

**Comment by cloudinjector** [comment]
我们暂时是没有用到so库的，不存在上面所说的情况。你应该看你的应用是否支持。
