### ISSUE TITLE
新功能：支持在公告或卡密等界面添加回复，反馈

### ISSUE THREAD

**Issue by SFSHTime** [cloudinjector/CloudInject#14]
就是类似有什么问题直接发送反馈的一个按键
也可以做一个私信界面，若有几个小时的卡密可以直接在云注入上面私信说明，然后创建者看到就可以回复，发送卡密。
这样就可以有很多种作用

**Comment by cloudinjector** [comment]
这个可能比较复杂，暂时不会考虑。

**Comment by SFSHTime** [comment]
好的，谢谢
